name: Build dB Studio EXE

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest # Usa uma máquina Windows oficial do GitHub (Grátis)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React and Electron EXE
        run: npm run dist # Este comando roda o electron-builder que configuramos no package.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dB-Studio-Windows-EXE
          path: release/*.exe # Busca o arquivo na pasta de saída
